/**
 * Model Configuration Component
 * Manages LLM model configurations
 */
import api from "../api.js";
import { showToast } from "../utils/helpers.js";

class ModelConfig {
  constructor() {
    this.modelPanel = null;
    this.isOpen = false;
    this.onModelAdded = null;
    this.currentModel = null; // For editing
    this.init();
  }

  init() {
    // Get references to existing HTML elements
    this.modelPanel = document.getElementById("model-config-panel");
    this.closeBtn = document.getElementById("close-model-config");
    this.cancelBtn = document.getElementById("cancel-model-btn");
    this.form = document.getElementById("model-config-form");
    this.agentModal = document.querySelector(".agent-modal-container");

    this.attachEventListeners();
  }

  attachEventListeners() {
    if (!this.modelPanel || !this.form) return;

    // Close button
    this.closeBtn?.addEventListener("click", () => this.close());

    // Cancel button
    this.cancelBtn?.addEventListener("click", () => this.close());

    // Form submission
    this.form.addEventListener("submit", (e) => this.handleSubmit(e));

    // Auto-fill model name based on provider
    const providerSelect = document.getElementById("model-provider");
    const modelNameInput = document.getElementById("model-name");
    const apiKeyNameInput = document.getElementById("model-api-key-name");

    providerSelect?.addEventListener("change", (e) => {
      const provider = e.target.value;
      const currentValue = modelNameInput.value;

      // Only auto-fill if empty or if it's a provider-prefixed value
      if (!currentValue || currentValue.includes("/")) {
        if (provider && provider !== "custom") {
          modelNameInput.placeholder = `${provider}/model-name`;
        }
      }

      // Auto-suggest env var name based on provider
      if (
        apiKeyNameInput &&
        (!apiKeyNameInput.value ||
          apiKeyNameInput.dataset.autoGenerated === "true")
      ) {
        if (provider && provider !== "custom") {
          const envVarName = `${provider.toUpperCase()}_API_KEY`;
          apiKeyNameInput.value = envVarName;
          apiKeyNameInput.dataset.autoGenerated = "true";
        }
      }
    });

    // Mark as user-edited when user types in api key name field
    apiKeyNameInput?.addEventListener("input", () => {
      if (apiKeyNameInput.value) {
        apiKeyNameInput.dataset.autoGenerated = "false";
      }
    });
  }

  async handleSubmit(e) {
    e.preventDefault();

    const formData = new FormData(e.target);
    const data = {
      display_name: formData.get("display_name"),
      model_name: formData.get("model_name"),
      provider: formData.get("provider"),
      api_key_name: formData.get("api_key_name") || null,
      api_key_value: formData.get("api_key_value") || null,
      supports_function_calling:
        formData.get("supports_function_calling") === "on",
      max_tokens: formData.get("max_tokens")
        ? parseInt(formData.get("max_tokens"))
        : null,
      description: formData.get("description") || null,
    };

    try {
      let result;

      if (this.currentModel) {
        // Update existing model
        result = await api.updateModel(this.currentModel.id, data);

        if (data.api_key_value) {
          showToast(
            `Model "${data.display_name}" updated successfully! API key saved to .env file.`,
            "success"
          );
        } else {
          showToast(
            `Model "${data.display_name}" updated successfully`,
            "success"
          );
        }
      } else {
        // Create new model
        result = await api.addModel(data);

        // Show success message with additional info if API key was added
        if (data.api_key_value) {
          showToast(
            `Model "${data.display_name}" added successfully! API key saved to .env file.`,
            "success"
          );
        } else {
          showToast(
            `Model "${data.display_name}" added successfully`,
            "success"
          );
        }
      }

      // Call the callback if provided
      if (this.onModelAdded) {
        this.onModelAdded(result);
      }

      this.close();
    } catch (error) {
      console.error("Error saving model:", error);
      showToast(error.message || "Failed to save model", "error");
    }
  }

  open(onModelAdded = null, existingModel = null) {
    this.onModelAdded = onModelAdded;
    this.currentModel = existingModel;
    this.isOpen = true;

    // Add class to agent modal container to show the panel
    if (this.agentModal) {
      this.agentModal.classList.add("model-panel-active");
    }

    // Populate form if editing
    if (existingModel) {
      document.getElementById("model-display-name").value =
        existingModel.display_name;
      document.getElementById("model-name").value = existingModel.model_name;
      document.getElementById("model-provider").value = existingModel.provider;
      document.getElementById("model-api-key-name").value =
        existingModel.api_key_name || "";
      document.getElementById("model-supports-functions").checked =
        existingModel.supports_function_calling;
      document.getElementById("model-max-tokens").value =
        existingModel.max_tokens || "";
      document.getElementById("model-description").value =
        existingModel.description || "";

      // Don't populate API key value for security
      document.getElementById("model-api-key-value").value = "";
      document.getElementById("model-api-key-value").placeholder =
        "Leave empty to keep existing key";
    } else {
      // Reset form for new model
      if (this.form) {
        this.form.reset();
      }
      document.getElementById("model-api-key-value").placeholder =
        "Enter your API key";
    }

    // Re-initialize Lucide icons
    if (window.lucide) {
      window.lucide.createIcons();
    }
  }

  close() {
    this.isOpen = false;
    this.currentModel = null;

    // Remove class from agent modal container to hide the panel
    if (this.agentModal) {
      this.agentModal.classList.remove("model-panel-active");
    }

    this.onModelAdded = null;
  }
}

// Export singleton instance
export default new ModelConfig();
